# Generated by Django 3.2.18 on 2023-03-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
