# Generated by Django 3.2.18 on 2023-03-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20230323_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='party_size',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
