# Generated by Django 3.2.18 on 2023-03-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20230326_1532'),
    ]

    operations = [
    ]
