# Generated by Django 3.2.18 on 2023-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
    ]
