# Generated by Django 3.2.18 on 2023-04-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_reservation_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
