# Generated by Django 3.2.18 on 2023-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_alter_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Reservation creation timestamp'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(help_text='Enter your email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Enter any special requests (optional)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', help_text='Select the reservation status', max_length=20),
        ),
    ]
