# Generated by Django 3.2.18 on 2023-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20230417_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(help_text='We will email you your booking', max_length=254),
        ),
    ]
