# Generated by Django 3.2.18 on 2023-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_reservation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
