# Generated by Django 3.2.18 on 2023-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Mains', 'Mains'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks'), ('Specials', 'Specials')], max_length=20, unique=True),
        ),
    ]
