# Generated by Django 3.2.18 on 2023-04-17 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menucategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Main Course', 'Main Course'), ('Desserts', 'Desserts'), ('Sides', 'Sides'), ('Specials', 'Specials')], help_text='Select the category', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=None, help_text='Select the category of the menu item', on_delete=django.db.models.deletion.CASCADE, to='menu.menucategory'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(help_text='Enter a description for the menu item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Enter the name of the menu item', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price of the menu item', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
